apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-reader
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-secrets-reader
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: secrets-reader
    namespace: dev
roleRef:
  kind: Role
  name: read-secrets
  apiGroup: rbac.authorization.k8s.io
